"""Transformations y = A*F(BX+C)+K (main menu 4). Study guide Section 5, cram sheet 5."""

BASE = ["t:4", "t:-4", "t:2", "t:-2", "t:-2", "t:1", "t:4", "t:3", "t:0", "k1"]  # base graph A,B,C,D, solid ends
BASE_SAVED = {"ʟBX": [-4, -2, 1, 3], "ʟBY": [2, -2, 4, 0], "ʟBC": [1, 1]}


def changes(cid, src, a, b, c, k, expect, official, path=None):
    return dict(id=cid, source=src, actions=["k4", "k1", f"t:{a}", f"t:{b}", f"t:{c}", f"t:{k}", "ENTER", "k2"],
                expect=expect, official=official,
                path=path or f"4 → 1:LIST THE CHANGES; A={a or 'ENTER'} B={b or 'ENTER'} C={c or 'ENTER'} K={k or 'ENTER'}")


def dr(cid, src, a, b, c, k, dom, rng, expect, official):
    acts = ["k4", "k3", f"t:{a}", f"t:{b}", f"t:{c}", f"t:{k}", "k1",
            f"t:{dom[0]}", f"t:{dom[1]}", "k1", f"t:{rng[0]}", f"t:{rng[1]}", "k1", "k2"]
    return dict(id=cid, source=src, actions=acts, expect=expect, official=official,
                path=f"4 → 3:NEW DOMAIN AND RANGE; A={a} B={b} C={c} K={k}; 1:D AND R; "
                     f"D {dom[0]} to {dom[1]} [ ]; R {rng[0]} to {rng[1]} [ ]")


CASES = [
    changes("REG-T1", "H(X)=-3F(X-2)+1", "-3", "", "-2", "1",
            ["Y=-3F(X-2)+1", "REFLECT OVER X-AXIS", "VERT STRETCH BY 3", "RIGHT 2", "UP 1"], "REFLECT X-AXIS, VERT STRETCH 3, RIGHT 2, UP 1"),
    changes("REG-T2", "F(4X-8) (student does not factor)", "", "4", "-8", "",
            ["Y=F(4(X-2))", "HORIZ COMPRESS BY 1/4", "RIGHT 2"], "HORIZ COMPRESS 1/4, RIGHT 2"),
    dict(id="REG-T3", source="2F((-4/3)X+4)-3, old point (-4,2)",
         actions=["k4", "k2", "t:2", "t:-4/3", "t:4", "t:-3", "k1", "t:-4", "t:2", "k2"],
         expect=["(6,1)"], official="(6,1)",
         path="4 → 2:NEW POINT(S); A=2 B=-4/3 C=4 K=-3; 1:TYPE ONE POINT; OLD X=-4 OLD Y=2"),
    dr("REG-T4", "2F((-4/3)X+4)-3 with Df=[-4,8], Rf=[-2,4]", "2", "-4/3", "4", "-3", ("-4", "8"), ("-2", "4"),
       ["D=[-3,6]", "R=[-7,5]"], "D=[-3,6], R=[-7,5]"),
    changes("PR-5.1", "State the transformations in order: y=-f(x-5)+2", "⁻", "", "-5", "2",
            ["REFLECT OVER X-AXIS", "RIGHT 5", "UP 2"], "Reflect over the x-axis; right 5; up 2."),
    changes("PR-5.2", "State the transformations in order: y=3f(1/2 x+2)-4", "3", "1/2", "2", "-4",
            ["Y=3F((1/2)(X+4))-4", "VERT STRETCH BY 3", "HORIZ STRETCH BY 2", "LEFT 4", "DOWN 4"],
            "Vertical stretch by 3; horizontal stretch by 2; left 4; down 4."),
    dict(id="PR-5.3", source="Mapping table for h(x)=-f(2x)+3 on the base graph; D_h and R_h",
         actions=["k4", "k2", "t:⁻", "t:2", "t:", "t:3", "k2"] + BASE + ["ENTER", "k2"],
         expect=["(-4,2) TO (-2,1)", "(-2,-2) TO (-1,5)", "(1,4) TO (1/2,-1)", "(3,0) TO (3/2,3)",
                 "D=[-2,3/2]  R=[-1,5]", "NEW X=(1/2)X", "NEW Y=-Y+3"],
         official="(-2,1), (-1,5), (1/2,-1), (3/2,3); D_h=[-2,3/2], R_h=[-1,5]",
         path="4 → 2:NEW POINT(S); A=(-) B=2 C=ENTER K=3; 2:ALL CORNERS; 4 points (-4,2) (-2,-2) (1,4) (3,0); 1:SOLID",
         graph="base graph corners typed from the figure"),
    dr("PR-5.4", "f: D=[-6,2], R=[-3,5]; k(x)=-2f(3x-3)+4", "-2", "3", "-3", "4", ("-6", "2"), ("-3", "5"),
       ["D=[-1,5/3]", "R=[-6,10]"], "D_k=[-1,5/3], R_k=[-6,10]"),
    dict(id="PR-5.5", source="Write an equation: vertical stretch by 5, horizontal compression by 1/2, right 3, down 1",
         actions=["k4", "k4", "k3", "t:5", "k4", "t:1/2", "k6", "t:3", "k8", "t:1", "k9", "k2"],
         expect=["Y=5F(2(X-3))-1", "=5F(2X-6)-1"], official="y=5f(2(x-3))-1 (=5f(2x-6)-1)",
         path="4 → 4:WRITE THE EQUATION; 3 then 5; 4 then 1/2; 6:RIGHT then 3; 8:DOWN then 1; 9:DONE"),
    changes("PR-5.6", "y=f(3x-12): correct 'shifted right 12'", "", "3", "-12", "",
            ["Y=F(3(X-4))", "HORIZ COMPRESS BY 1/3", "RIGHT 4"], "horizontal compression by 1/3, then right 4, not 12"),
    changes("EX-5.1a", "h(x)=2f(x+1)-3: transformations", "2", "", "1", "-3",
            ["VERT STRETCH BY 2", "LEFT 1", "DOWN 3"], "vertical stretch by 2; left 1; down 3"),
    dict(id="EX-5.1b", source="h(x)=2f(x+1)-3: mapping table on the base graph, D_h, R_h",
         actions=["k4", "k2", "t:2", "t:", "t:1", "t:-3", "k2", "k1", "k2"], lists=BASE_SAVED,
         expect=["(-4,2) TO (-5,1)", "(-2,-2) TO (-3,-7)", "(1,4) TO (0,5)", "(3,0) TO (2,-3)",
                 "D=[-5,2]  R=[-7,5]", "NEW X=X-1", "NEW Y=2Y-3"],
         official="(-5,1), (-3,-7), (0,5), (2,-3); D_h=[-5,2], R_h=[-7,5]",
         path="4 → 2; A=2 B=ENTER C=1 K=-3; 2:ALL CORNERS; 1:USE SAVED GRAPH"),
    changes("EX-5.2a", "g(x)=f(3x+6)-1", "", "3", "6", "-1",
            ["Y=F(3(X+2))-1", "HORIZ COMPRESS BY 1/3", "LEFT 2", "DOWN 1"], "Horizontal compression by 1/3, left 2 (not left 6), down 1."),
    changes("EX-5.2b", "y=f(2x-6)", "", "2", "-6", "", ["Y=F(2(X-3))", "HORIZ COMPRESS BY 1/2", "RIGHT 3"],
            "horizontal compression by 1/2, right 3"),
    changes("EX-5.2c", "y=f(-x+3)", "", "⁻", "3", "", ["Y=F(-(X-3))", "REFLECT OVER Y-AXIS", "RIGHT 3"], "reflect over the y-axis, right 3"),
    changes("EX-5.3a", "h(x)=-1/2 f(-2x+4)+1", "-1/2", "-2", "4", "1",
            ["Y=(-1/2)F(-2(X-2))+1", "REFLECT OVER X-AXIS", "VERT COMPRESS BY 1/2", "REFLECT OVER Y-AXIS",
             "HORIZ COMPRESS BY 1/2", "RIGHT 2", "UP 1", "A=-1/2  B=-2  H=2  K=1"],
            "reflect over the x-axis; vertical compression by 1/2; reflect over the y-axis; "
            "horizontal compression by 1/2; right 2; up 1"),
    dict(id="EX-5.3b", source="h(x)=-1/2 f(-2x+4)+1: table and D, R", lists=BASE_SAVED,
         actions=["k4", "k2", "t:-1/2", "t:-2", "t:4", "t:1", "k2", "k1", "k2"],
         expect=["(-4,2) TO (4,0)", "(-2,-2) TO (3,2)", "(1,4) TO (3/2,-1)", "(3,0) TO (1/2,1)",
                 "D=[1/2,4]  R=[-1,2]", "NEW X=-(1/2)X+2", "NEW Y=-(1/2)Y+1"],
         official="(4,0), (3,2), (3/2,-1), (1/2,1); D_h=[1/2,4], R_h=[-1,2]",
         path="4 → 2; A=-1/2 B=-2 C=4 K=1; 2:ALL CORNERS; 1:USE SAVED GRAPH"),
    dr("EX-5.4", "f: D=[-3,5], R=[-2,6]; h(x)=4f(-1/2x+3)-1", "4", "-1/2", "3", "-1", ("-3", "5"), ("-2", "6"),
       ["D=[-4,12]", "R=[-9,23]"], "D_h=[-4,12], R_h=[-9,23]"),
    dict(id="EX-5.5i", source="Horizontal stretch by a factor of 3, then shift left 2",
         actions=["k4", "k4", "k4", "t:3", "k5", "t:2", "k9", "k2"],
         expect=["Y=F((1/3)(X+2))"], official="y=f(1/3(x+2))",
         path="4 → 4; 4 then 3; 5:LEFT then 2; 9:DONE"),
    dict(id="EX-5.5ii", source="Reflect over the x-axis, then shift down 4",
         actions=["k4", "k4", "k1", "k8", "t:4", "k9", "k2"], expect=["Y=-F(X)-4"], official="y=-f(x)-4",
         path="4 → 4; 1; 8:DOWN then 4; 9:DONE"),
    dict(id="EX-5.5iii", source="Shift down 4, THEN reflect over the x-axis",
         actions=["k4", "k4", "k8", "t:4", "k1", "k9", "k2"], expect=["Y=-F(X)+4"], official="y=-(f(x)-4)=-f(x)+4",
         path="4 → 4; 8:DOWN then 4; 1; 9:DONE"),
    changes("CRAM-5a", "h=2f(-4/3x+4)-3", "2", "-4/3", "4", "-3",
            ["Y=2F((-4/3)(X-3))-3", "VERT STRETCH BY 2", "REFLECT OVER Y-AXIS", "HORIZ COMPRESS BY 3/4",
             "RIGHT 3", "DOWN 3"],
            "vertical stretch by 2, reflect over y-axis, horizontal compression by 3/4, right 3, down 3"),
    dr("CRAM-5b", "Df=[-2,6], Rf=[-1,7], h=-5f(-1/3x-6)+4", "-5", "-1/3", "-6", "4", ("-2", "6"), ("-1", "7"),
       ["D=[-36,-12]", "R=[-31,9]"], "D_h=[-36,-12]; R_h=[-31,9]"),
    changes("CRAM-5c", "-f(x)+3", "⁻", "", "", "3", ["REFLECT OVER X-AXIS", "UP 3"], "reflect, then up 3"),
    changes("CRAM-5d", "f(4x-2)", "", "4", "-2", "", ["Y=F(4(X-1/2))", "HORIZ COMPRESS BY 1/4", "RIGHT 1/2"], "right 1/2 (after compress)"),
    dict(id="CORR-1", source="Quiz review #1 (corrected): h(x)=-2f(-x)+3 on f's points (-4,0),(-3,4),(0,-2),(2,2)",
         actions=["k4", "k2", "t:-2", "t:⁻", "t:", "t:3", "k2", "t:4", "t:-4", "t:0", "t:-3", "t:4", "t:0", "t:-2",
                  "t:2", "t:2", "k1", "ENTER", "k2"],
         expect=["(-4,0) TO (4,3)", "(-3,4) TO (3,-5)", "(0,-2) TO (0,7)", "(2,2) TO (-2,-1)",
                 "D=[-2,4]  R=[-5,7]", "NEW X=-X", "NEW Y=-2Y+3"],
         official="(4,3), (3,-5), (0,7), (-2,-1); range [-5,7] (not [-7,7]); domain [-2,4]",
         path="4 → 2:NEW POINT(S); A=-2 B=(-) C=ENTER K=3; 2:ALL CORNERS; 4 points; 1:SOLID",
         graph="the quiz's points typed in"),
]

# ---------------------------------------------------------------------------------------------
# Adversarial review (REV-trans-n): one case per bug fixed or friction removed, so it stays fixed.
# ---------------------------------------------------------------------------------------------
BASE_PTS = ["t:4", "t:-4", "t:2", "t:-2", "t:-2", "t:1", "t:4", "t:3", "t:0"]  # HAPTS: 4 corners
CASES += [
    dict(id="REV-trans-1", source="flat 2-point graph, both end dots hollow: h(x)=2f(x)+1 on (0,3),(4,3)",
         actions=["k4", "k2", "t:2", "t:", "t:", "t:1", "k2", "t:2", "t:0", "t:3", "t:4", "t:3", "k4",
                  "ENTER", "k2"],
         expect=["(0,3) TO (0,7)", "(4,3) TO (4,7)", "D=(0,4)  R=[7,7]"],
         official="range {7} = [7,7] (was printed (7,7), an empty interval)",
         path="4 → 2 → A=2 B,C=ENTER K=1 → 2:ALL CORNERS → 2 points → 4:BOTH OPEN"),
    dict(id="REV-trans-2", source="A=0 then B=0 typed by mistake: refused, screen redrawn (no scrolling)",
         actions=["k4", "k1", "t:0", "t:2", "t:0", "t:2", "t:", "t:1", "t:-3", "ENTER", "k2"],
         expect=["Y=2F(X+1)-3", "VERT STRETCH BY 2", "LEFT 1", "DOWN 3"],
         official="vertical stretch by 2; left 1; down 3 (EX-5.1)",
         path="4 → 1 → A=0 (asked again) A=2 B=0 (asked again) A=2 B=ENTER C=1 K=-3"),
    dict(id="REV-trans-3", source="write the equation: a long result (was a Disp wider than 26 on SO FAR)",
         actions=["k4", "k4", "k3", "t:5/3", "k4", "t:6", "k2", "k6", "t:324/7", "k8", "t:1/3", "k9",
                  "ENTER", "k2"],
         expect=["=(5/3)F(-(1/6)X+54/7)-1/3", "A=5/3  B=-1/6", "H=324/7  K=-1/3"],
         official="y = 5/3 f(-1/6 (x - 324/7)) - 1/3 = 5/3 f(-1/6 x + 54/7) - 1/3",
         path="4 → 4; 3:5/3; 4:6; 2; 6:RIGHT 324/7; 8:DOWN 1/3; 9"),
    dict(id="REV-trans-4", source="write: up 1/3, vertical stretch 3, down 1 (was Y=3F(X)-0)",
         actions=["k4", "k4", "k7", "t:1/3", "k3", "t:3", "k8", "t:1", "k9", "ENTER", "k2"],
         expect=["Y=3F(X)", "A=3  B=1  H=0  K=0"], official="y = 3f(x)",
         path="4 → 4; 7:UP 1/3; 3:3; 8:DOWN 1; 9"),
    dict(id="REV-trans-5", source="write: vertical compress 1/3 then stretch 3 (was Y=1F(X))",
         actions=["k4", "k4", "k3", "t:1/3", "k3", "t:3", "k9", "ENTER", "k2"],
         expect=["Y=F(X)", "A=1  B=1  H=0  K=0"], official="y = f(x)",
         path="4 → 4; 3:1/3; 3:3; 9"),
    dict(id="REV-trans-6", source="EX-5.1 typed with the plus signs the student sees: C=+1 (was ERR:SYNTAX)",
         actions=["k4", "k1", "t:2", "t:", "t:+1", "t:-3", "ENTER", "k2"],
         expect=["Y=2F(X+1)-3", "VERT STRETCH BY 2", "LEFT 1", "DOWN 3", "A=2  B=1  H=-1  K=-3"],
         official="vertical stretch by 2; left 1; down 3",
         path="4 → 1 → A=2 B=ENTER C=+1 K=-3"),
    dict(id="REV-trans-7", source="g(x)=f(3x+6)-1 with B typed as 3X and K as +... (was B=6, a wrong answer)",
         actions=["k4", "k1", "t:", "t:3X", "t:+6", "t:-1", "ENTER", "k2"],
         expect=["Y=F(3(X+2))-1", "HORIZ COMPRESS BY 1/3", "LEFT 2", "DOWN 1"],
         official="Horizontal compression by 1/3, left 2 (not left 6), down 1 (EX-5.2)",
         path="4 → 1 → A=ENTER B=3X C=+6 K=-1"),
    dict(id="REV-trans-8", source="saved graph lists out of step (dims differ): asks for the graph (was ERR:DIM MISMATCH)",
         lists={"ʟBX": [1, 2], "ʟBY": [3], "ʟBC": [1, 1]},
         actions=["k4", "k2", "t:2", "t:", "t:1", "t:-3", "k2"] + BASE_PTS + ["k1", "ENTER", "k2"],
         expect=["(-4,2) TO (-5,1)", "(3,0) TO (2,-3)", "D=[-5,2]  R=[-7,5]", "NEW X=X-1", "NEW Y=2Y-3"],
         official="(-5,1), (-3,-7), (0,5), (2,-3); D_h=[-5,2], R_h=[-7,5] (EX-5.1)",
         path="4 → 2 → A=2 B=ENTER C=1 K=-3 → 2:ALL CORNERS → (typed, the bad saved lists are not offered)"),
    dict(id="REV-trans-9", source="CRAM-EX-5a both parts with one equation: changes, 3:SAME EQ, D and R",
         actions=["k4", "k1", "t:2", "t:-(4/3)", "t:4", "t:-3", "ENTER", "k3", "k3", "k1",
                  "t:-4", "t:8", "k1", "t:-2", "t:4", "k1", "k2"],
         expect=["Y=2F((-4/3)(X-3))-3", "VERT STRETCH BY 2", "REFLECT OVER Y-AXIS", "HORIZ COMPRESS BY 3/4",
                 "RIGHT 3", "DOWN 3", "D=[-3,6]", "R=[-7,5]"],
         official="vertical stretch by 2, reflect over y-axis, horizontal compression by 3/4, right 3, down 3; "
                  "D_h=[-3,6]; R_h=[-7,5]",
         path="4 → 1 → A=2 B=-(4/3) C=4 K=-3 → 3:SAME EQ → 3:D AND R → 1 → D -4,8 [ ] → R -2,4 [ ]"),
    dict(id="REV-trans-10", source="EX-5.3 all parts with one equation: changes, 3:SAME EQ, table (saved graph)",
         lists=BASE_SAVED,
         actions=["k4", "k1", "t:-1/2", "t:-2", "t:4", "t:1", "ENTER", "k3", "k2", "k2", "k1", "ENTER", "k2"],
         expect=["Y=(-1/2)F(-2(X-2))+1", "REFLECT OVER X-AXIS", "VERT COMPRESS BY 1/2", "A=-1/2  B=-2  H=2  K=1",
                 "(-4,2) TO (4,0)", "(-2,-2) TO (3,2)", "(1,4) TO (3/2,-1)", "(3,0) TO (1/2,1)",
                 "D=[1/2,4]  R=[-1,2]", "NEW X=-(1/2)X+2", "NEW Y=-(1/2)Y+1"],
         official="a=-1/2, b=-2, h=2, k=1; A'(4,0), B'(3,2), C'(3/2,-1), D'(1/2,1); D_h=[1/2,4], R_h=[-1,2]; "
                  "rules x -> -1/2 x + 2, y -> -1/2 y + 1",
         path="4 → 1 → A=-1/2 B=-2 C=4 K=1 → 3:SAME EQ → 2:NEW POINTS → 2:ALL CORNERS → 1:USE SAVED"),
    dict(id="REV-trans-11", source="PR-5.5's equation, then 3:SAME EQ → the new point of (4,2)",
         actions=["k4", "k4", "k3", "t:5", "k4", "t:1/2", "k6", "t:3", "k8", "t:1", "k9", "k3", "k2", "k1",
                  "t:4", "t:2", "k2"],
         expect=["Y=5F(2(X-3))-1", "(5,9)", "FROM (4,2)"],
         official="y=5f(2(x-3))-1 maps (4,2) to (4/2+3, 5*2-1) = (5,9)",
         path="4 → 4 → 3:5 4:1/2 6:RIGHT 3 8:DOWN 1 9 → 3:SAME EQ → 2 → 1:ONE POINT → 4, 2"),
    dict(id="REV-trans-12", source="write: 'shift left 2' typed as -2 still means left 2 (sizes are taken as seen)",
         actions=["k4", "k4", "k4", "t:3", "k5", "t:-2", "k9", "k2"],
         expect=["Y=F((1/3)(X+2))"], official="y=f(1/3(x+2)) (EX-5.5 i)",
         path="4 → 4; 4:3; 5:LEFT -2; 9"),
    dict(id="REV-trans-13", source="long table lines are split before the new point, never inside a number",
         actions=["k4", "k2", "t:-5/7", "t:3/11", "t:1/2", "t:-2/9", "k2", "t:2", "t:-7/3", "t:7/2",
                  "t:5/4", "t:-9/2", "k1", "ENTER", "k2"],
         expect=["(-7/3,7/2) TO", "(-187/18,-49/18)", "(5/4,-9/2) TO", "(11/4,377/126)",
                 "D=[-187/18,11/4]", "R=[-49/18,377/126]", "NEW X=(11/3)X-11/6", "NEW Y=-(5/7)Y-2/9"],
         official="(x,y) -> ((x-1/2)/(3/11), -5/7 y - 2/9)",
         path="4 → 2 → A=-5/7 B=3/11 C=1/2 K=-2/9 → 2:ALL CORNERS → 2 points"),
    dict(id="REV-trans-14", source="y=f(x/2)+1 with B typed as X/2 (was read with X's leftover value: B=3/2)",
         actions=["k4", "k1", "t:", "t:X/2", "t:", "t:+1", "ENTER", "k2"],
         expect=["Y=F((1/2)X)+1", "HORIZ STRETCH BY 2", "UP 1", "A=1  B=1/2  H=0  K=1"],
         official="horizontal stretch by 2, up 1",
         path="4 → 1 → A=ENTER B=X/2 C=ENTER K=+1"),
]
